spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fin_assistant?currentSchema=fin_assistant
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
    openInView: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    hidden-method:
      filter:
        enabled: true